# Generated by Django 6.0.5 on 2026-06-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('free', 'Free'), ('lend', 'Lend'), ('sell', 'Sell')], default='free', max_length=10),
        ),
    ]
