# Generated by Django 6.0.5 on 2026-06-10 17:12

import listings.models
from django.db import migrations, models
from cloudinary.models import CloudinaryField


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resource_images/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=CloudinaryField(
                resource_type="raw",
                blank=True,
                null=True,
            ),
        ),
    ]
