# Generated by Django 6.0.5 on 2026-06-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_resource_image_alter_resource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], null=True),
        ),
    ]
