# Generated by Django 6.0.5 on 2026-05-31 08:36

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_resource_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to=listings.models.resource_file_path),
        ),
    ]
