# Generated by Django 6.0.5 on 2026-06-10 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_resource_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='image',
        ),
        migrations.CreateModel(
            name='ResourceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resource_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.resource')),
            ],
        ),
    ]
