# Generated by Django 6.0.5 on 2026-06-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_resource_image_resourceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resource_images/'),
        ),
        migrations.DeleteModel(
            name='ResourceImage',
        ),
    ]
