# Generated by Django 6.0.5 on 2026-06-14 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_resource_image_delete_resourceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resource_images/')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='listings.resource')),
            ],
        ),
    ]
