# Generated by Django 5.2 on 2026-06-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_resourceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('lent', 'Lent'), ('sold', 'Sold')], default='available', max_length=10),
        ),
    ]
